# config/database.yml: Using psb_user with password and host (free, open-source).
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: psb_user
  password: testpassword  # This is the password to match.
  host: localhost  # Forces TCP to avoid socket issues.

development:
  <<: *default
  database: payroll-rails_development

test:
  <<: *default
  database: payroll-rails_test